### ISSUE TITLE
 Make YNR a crowd-sourcing site for politicians

### ISSUE THREAD

**Issue by martinszy** [ConocimientoAbierto/policrowd#1]
Rationale: After elections are over, all YNR sites are useless until the next election. Allowing the sites to collect information on politicians is the way to keep sites alive.
- [ ] Create "nomination" model #3 
- [ ] Allow candidate to be with elections or nominations #4 
- [ ] Remove candidate's dependency on party (not all public servants belong to a party) #5 
- [ ] Rename "candidate" model to "politician" #6 
- [ ] Allow for flexibility in older elections and nominations #7 

Copied from: https://github.com/mysociety/yournextrepresentative/issues/697

**Comment by martinszy** [comment]
Falta terminar de implementar el diseño, pero ya está.
